### ISSUE TITLE
崩溃 

### ISSUE THREAD

**Issue by ZZKll** [chenliangloveyou/EasyNavigation#15]
[EasyNavigationView addLeftView:callback:]: unrecognized selector sent to instance 0x7fac1842eaf0

tabbar 其中的一个ViewController 用这个库包含 例如 
 HomeViewController *homeView = [HomeViewController new];
    EasyNavigationController *homeNav = [[EasyNavigationController alloc]initWithRootViewController:homeView];
 self.viewControllers = @[newsNav,liveNav,homeNav,governmentNav,peopleLiveNav];

在ViewController里 调用方法崩溃

**Comment by chenliangloveyou** [comment]
[EasyNavigationView addLeftView:callback:]: unrecognized selector sent to instance 0x7fac1842eaf0

改成
    [self.navigationView addSubview:xxxclickCallback:nil];

**Comment by ZZKll** [comment]
已改 谢谢 
关于 LineView 的设置好像没有效果 例如 
[self.navigationView setLineViewHidden:YES]

还是能看到一个小白条 .

**Comment by chenliangloveyou** [comment]
self.navigationView.lineView.hidden  = yes ;

**Comment by ZZKll** [comment]
ok .谢啦 大佬
