### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [chenliangloveyou/EasyNavigation#17]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before

**Comment by chenliangloveyou** [comment]
Glad to hear that.Looking forward to your production.

**Comment by anharismail** [comment]
Hello @chenliangloveyou , this is my logo proposal for your project. This logo was inspired by navigation bar and 'E' initial. I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

![easynavigation ver 1](https://user-images.githubusercontent.com/37614260/46578076-77f2d500-ca1f-11e8-8e41-702e41d25539.png)

**Comment by anharismail** [comment]
Hello @chenliangloveyou , I've created another idea for my logo design proposal. This design comes with better shape and color combination, also with another logotype.

Here it is.

![easynavigation ver 2](https://user-images.githubusercontent.com/37614260/46787059-e78afc00-cd60-11e8-85ba-64e73573130b.png)

**Comment by chenliangloveyou** [comment]
OK，i love it , thanks very much,you can send a marge request . i will marge it . and use this logo on my project.

**Comment by anharismail** [comment]
Thanks for your response. I'll provide it soon
