### ISSUE TITLE
使用UISearchController做搜索跳转,点击cancel的回来的时候,系统导航栏出现了

### ISSUE THREAD

**Issue by yufanghui** [chenliangloveyou/EasyNavigation#26]
使用UISearchController的searchBar作为tableView的tableHeaderView,点击searchBar,会调用系统的转场,跳转到搜索页面,
在搜索页面,点击取消,搜索页面消失,前一个页面出现,系统的导航条也出来了

**Comment by Liyongcong** [comment]
我也遇到这个问题了，有解决方案吗
